#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

bar=(
  position=top
  height=36
  blur_radius=30 
  color=$BAR_COLOR
  margin=12
  y_offset=8
  corner_radius=8
  border_color=$BAR_BORDER_COLOR
  border_width=1
)
sketchybar --bar "${bar[@]}"

default=(
  padding_left=2
  padding_right=2
  icon.font="SF Pro:Semibold:15.0"
  label.font="SF Pro:Semibold:14.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=8
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=8
  background.color=$ITEM_BG_COLOR
  background.corner_radius=5
  background.height=24
)
sketchybar --default "${default[@]}"

# -- Left Side Items --
source $ITEM_DIR/apple.sh
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# --- Right Side Items ---
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh

sketchybar --update
